### ISSUE TITLE
docker needs root permissions in cloud vm

### ISSUE THREAD

**Issue by riebling** [liboyue/BOOM#2]
How do you work around docker giving errors when you run it as simply `docker` rather than `sudo docker`? Was the VM you work in provisioned to allow docker without root privileges (that'd be nice!)

Otherwise the stuff in `bin/boom` might need sudo. So working around this by prefacing command with sudo, here's some more exciting error output(!)
```
ubuntu@ip-172-31-15-172:~/BOOM/examples/toy$ sudo ../../bin/boom conf.yaml
W0814 18:33:57.905799 31629 boom:159] The experiment name is: 2018-08-14_18h33m57s
W0814 18:34:03.297464 31629 boom:204] Loglevel: INFO
W0814 18:34:03.297706 31629 boom:205] Loaded configuration file from: conf.yaml
W0814 18:34:03.297781 31629 boom:206] Running mode: docker
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/a500c4737b6d242666c92d97d81a80\
1aa2076777a683782d369b776240a46d4f/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../bin/boom", line 304, in <module>
    containers.append(start_container(client, 'python3 /code.zip -verbosity=' + FLAGS.verbosity, dir_name.replace('/', ''), volumes={os.pat\
h.abspath(dir_name) + '.zip': {'bind': '/code.zip', 'mode': 'rw'}}))
  File "../../bin/boom", line 119, in start_container
    detach=True
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/models/containers.py", line 772, in run
    container.start()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/models/containers.py", line 374, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/container.py", line 1066, in start
    self._raise_for_status(res)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("invalid header field value "oci runtime error: container_linux.go:247: starting conta\
iner process caused \"exec: \\\"python3\\\": executable file not found in $PATH\"\n"")
```
Ok the `python3` not in path seems kind of serious, so I tried the not-recommended creating a symbolic link `/usr/bin/python -> /usr/bin/python3` and ran again, to learn:
```
ubuntu@ip-172-31-15-172:~/BOOM/examples/toy$ sudo ../../bin/boom conf.yaml
W0814 19:06:49.614297 32443 boom:159] The experiment name is: 2018-08-14_19h06m49s
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=rabbitmq
ubuntu@ip-172-31-15-172:~/BOOM/examples/toy$ sudo ../../bin/boom conf.yaml
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../bin/boom", line 174, in <module>
    rabbitmq = start_container(client, 'rabbitmq-server', 'rabbitmq')
  File "../../bin/boom", line 109, in start_container
    detach=True
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/models/containers.py", line 766, in run
    detach=detach, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/models/containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/container.py", line 411, in create_container
    return self.create_container_from_config(config, name)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/container.py", line 422, in create_container_from_config
    return self._result(res, True)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/rabbitmq" is already in use by container 2fb4b8e9c20a117090f322a108742655b0de8a6e4b007c529ac775c65d574a70. You have to remove (or rename) that container to be able to reuse that name.")
```

**Comment by liboyue** [comment]
Please refer to https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04

**Comment by liboyue** [comment]
I think the first problem is caused by `sudo`. Because if you `sudo` something, you have to pass the same environment vars. All dependencies should be installed in your user dir, but not in root's dir.

The second problem is because you didn't shut down the docker containers. I'll add a check in the code.

**Comment by riebling** [comment]
This is good. Maybe we can add some examples of basic commands like starting/stopping containers. It's nice, though, you have things so well configured & configurable that simply running `boom` can get all it needs from .yaml files etc. :)

**Comment by liboyue** [comment]
Done
